server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://rm-uf659fc1pyp136g328o.mysql.rds.aliyuncs.com:3306/zx-bt?useSSL=false
    username: root
    password: Lzb112358*
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
security:
  basic:
    enabled: false
zx-bt:
  main:
    ports:
      - 44444
      - 44445
      - 44446
    ip: 183.128.108.198
    init-addresses:
      - 213.136.79.7:6892
      - 173.212.205.4:6876
      - 213.136.79.7:6976
      - 5.79.71.112:51416
      - 213.136.79.238:51504
      - 173.212.205.4:6879
      - 5.189.187.90:6961
      - 85.17.21.107:6881
      - 98.251.201.168:4620
      - 176.221.7.197:6881
      - 179.100.61.253:3111
      - 89.128.212.243:80
      - 101.177.111.96:2101
      - 46.174.123.54:59528
      - 73.183.227.53:6889
      - 89.158.99.95:42060
      - 78.131.103.118:6881
      - 86.166.54.181:6881
      - 68.33.103.62:39939
      - 36.232.112.51:8576
      - 69.9.68.167:10099
      - 113.75.10.73:45620
      - 85.173.163.72:6881
      - 109.61.242.74:11609
      - 216.229.76.101:6881
      - 109.87.189.79:45320
      - 109.87.238.34:11656
      - 93.81.205.100:38682
      - 176.118.55.20:53532
      - 84.236.28.57:6881
      - 178.164.128.95:6881
      - 37.220.35.79:6881
      - 37.59.58.55:6881
      - 188.165.211.227:6881
      - 94.23.249.8:6881
      # 以下是比较有名的节点.其中utorrent是比较好的.剩余两个有点垃圾
      - router.utorrent.com:6881
      - router.bittorrent.com:6881
      - router.bitcomet.com:6881
      - dht.transmissionbt.com:6881
      # 以下是返回我有效的get_peers请求的节点
      - 185.106.123.2:28013
      - 5.79.77.167:6881
      - 185.45.195.187:28161
      - 173.193.90.75:15005
      - 178.32.217.107:1026
      - 185.148.3.126:15359
      - 223.190.104.156:16771
      - 91.226.172.12:6881
      - 188.163.9.89:36812
